# backend/models/dna.py

from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime

# -----------------------------
# DNA Record Access Level
# -----------------------------
AccessLevel = Literal[
    "medical",
    "forensic",
    "research"
]

# -----------------------------
# DNA Record Model
# -----------------------------
class DNARecord(BaseModel):
    record_id: Optional[str] = Field(
        default=None,
        description="Generated by backend"
    )
    dna_sequence: str = Field(
        ...,
        description="Raw DNA sequence (stored off-chain)"
    )
    owner: str = Field(
        ...,
        description="Username of the data owner"
    )
    access_level: AccessLevel
    created_at: Optional[datetime] = Field(
        default=None,
        description="Set by backend"
    )
